# Default values for micro-auth.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: ibmcase/bluecompute-auth
  tag: latest 
  pullPolicy: IfNotPresent

resources:
limits:
  memory: 128Mi
requests:
  memory: 64Mi

service:
  name: auth-service
  type: ClusterIP
  externalPort: 8080
  internalPort: 8080

hs256key:
  skipDelete: true
  secretName: hs256-key

