# Default values for micro-auth.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 2

image:
  repository: ibmcase/bluecompute-auth
  tag: latest 
  pullPolicy: Always

service:
  name: auth-service
  type: ClusterIP
  externalPort: 8080
  internalPort: 8080

hs256key:
  skipDelete: false
  secretName: hs256-key

resources:
  limits:
    cpu: 1000m
    memory: 512Mi
  requests:
    cpu: 1000m
    memory: 512Mi