apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
  labels:
    app: bluecompute
    micro: auth
    tier: backend
    release: {{.Release.Name | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: bluecompute
        micro: auth
        tier: backend
        release: {{.Release.Name | quote }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
      annotations:
        pod.beta.kubernetes.io/init-containers: '[
          {
            "name": "test-customer-service",
            "image": "ibmcase/mysql-loader:latest",
            "imagePullPolicy": "IfNotPresent",
            "command": ["/bin/bash", "-c"], 
            "args": ["until curl http://customer-service:8080; do echo waiting for customer-service; sleep 1; done"]
          }
        ]'
    spec:
      containers:
      - name: {{ .Release.Name }}-{{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        volumeMounts:
        - mountPath: /var/run/secrets/hs256-key
          name: hs256-key
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
      - name: hs256-key
        secret:
          defaultMode: 420
          secretName: "{{ .Chart.Name }}-{{ .Values.hs256key.secretName }}"
